# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.continuum.io/pkgs/main/win-64/ca-certificates-2018.03.07-0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/vs2015_runtime-14.0.25123-3.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/vc-14-h0510ff6_3.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/openssl-1.0.2o-h8ea7d77_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/python-3.6.5-h0c2934d_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/asn1crypto-0.24.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/certifi-2018.1.18-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/chardet-3.0.4-py36h420ce6e_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/idna-2.6-py36h148d497_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pycparser-2.18-py36hd053e01_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pytz-2018.3-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/six-1.11.0-py36h4db2310_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/win_inet_pton-1.0.1-py36he67d7fd_1.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/wincertstore-0.2-py36h7fe50ca_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/cffi-1.11.5-py36h945400d_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/django-2.0.2-py36hd476221_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pysocks-1.6.8-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/setuptools-39.0.1-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/cryptography-2.2.2-py36hfa6e2cd_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/wheel-0.31.0-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pip-9.0.3-py36_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/pyopenssl-17.5.0-py36h5b7d817_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/urllib3-1.22-py36h276f60a_0.tar.bz2
https://repo.continuum.io/pkgs/main/win-64/requests-2.18.4-py36h4371aae_1.tar.bz2
