# Generated by Django 2.0.2 on 2018-04-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Objective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('objective_achieved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_status', models.CharField(blank=True, choices=[('PWBS', 'Past week before singup'), ('PWNO', 'Past week no objective'), ('PWMO', 'Past week missed objective'), ('PWOA', 'Past week objective achieved'), ('CWNO', 'Current week no objective'), ('CWWO', 'Current week with objective'), ('CWOA', 'Current week objective achieved'), ('FWNO', 'Future week no objective'), ('FWWO', 'Future week with objective')], max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='objective',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Week'),
        ),
    ]
