# Generated by Django 2.0.2 on 2018-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20180401_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='life_expectancy',
            field=models.IntegerField(null=True),
        ),
    ]
