# Generated by Django 2.0.2 on 2018-04-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_life_expectancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='life_in_weeks',
            field=models.IntegerField(null=True),
        ),
    ]
